Repository FintechInternshipCourse-Dongas/backend, pull requests merged in 2024-08, with the labels that each got.

#4 공통 모듈 구성 및 프로젝트 기본 설정
  build.gradle
  src/main/java/com/core/backend/FintechBackendApplication.java
  src/main/java/com/core/backend/common/exception/DefaultException.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/backend/common/exception/global/GlobalException.java
  src/main/java/com/core/backend/common/repsonse/ResultResponse.java
  src/main/java/com/core/backend/config/SwaggerConfig.java
  src/main/java/com/core/backend/config/WebConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/core/backend/FintechBackendApplicationTests.java
Labels: 모임, 모임관리

#43 사용자가 참여한 모임방 조회 Mock API 작성
  src/main/java/com/core/backend/common/mock/GetAllGroupMockData.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupInfoResponse.java
Labels: be, 모임방조회

#44 모임방 별 정산내역 요약 조회 mock API 작성
  src/main/java/com/core/backend/common/mock/GetGroupSettlementMockData.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupMemberResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupSettlementListResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupSettlementResponse.java
Labels: be, 정산

#46 개발 서버 연동 github Actions script 작성
  .github/workflows/deploy.yml
  scripts/deploy.sh
  src/main/java/com/core/backend/common/healthcheck/HealthCheckController.java
Labels: be, 프로젝트세팅

#53 사용자 일반 회원가입 기능 API 구현
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/user/application/UserCommandService.java
  src/main/java/com/core/backend/user/application/UserQueryService.java
  src/main/java/com/core/backend/user/application/dto/UserSignUpServiceRequest.java
  src/main/java/com/core/backend/user/domain/PasswordEncryptor.java
  src/main/java/com/core/backend/user/domain/repository/UserRepository.java
  src/main/java/com/core/backend/user/exception/UserException.java
  src/main/java/com/core/backend/user/infra/database/JpaUserRepository.java
  src/main/java/com/core/backend/user/infra/database/UserRepositoryImpl.java
  src/main/java/com/core/backend/user/infra/encryption/AESAlgEncryptor.java
  src/main/java/com/core/backend/user/ui/UserController.java
  src/main/java/com/core/backend/user/ui/dto/UserSignUpRequest.java
  src/main/resources/static/favicon.ico
  src/test/java/com/core/backend/user/domain/UserTest.java
Labels: be, 회원, 회원가입

#58 모임방 생성 API 작성
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/common/initializer/DataInitializer.java
  src/main/java/com/core/backend/config/SwaggerConfig.java
  src/main/java/com/core/backend/config/WebConfig.java
  src/main/java/com/core/backend/group/application/GroupCommandService.java
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/group/application/dto/GroupRegisterServiceRequest.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/group/domain/repository/GroupRepository.java
  src/main/java/com/core/backend/group/infra/GroupRepositoryImpl.java
  src/main/java/com/core/backend/group/infra/JpaGroupRepository.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupRegisterRequest.java
  src/main/java/com/core/backend/user/application/UserCommandService.java
  src/main/java/com/core/backend/user/domain/Password.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/java/com/core/backend/user/domain/repository/UserRepository.java
  src/main/java/com/core/backend/user/infra/database/UserRepositoryImpl.java
  src/main/java/com/core/backend/user/ui/dto/UserSignUpRequest.java
  src/test/java/com/core/backend/group/GroupServiceTestFixture.java
  src/test/java/com/core/backend/group/application/GroupCommandServiceTest.java
  src/test/java/com/core/backend/user/domain/UserTest.java
Labels: 모임, be, 모임방생성

#60 사용자가 참여한 모임방 조회 기능 API 작성
  src/main/java/com/core/backend/auth/application/UserAuthCommandService.java
  src/main/java/com/core/backend/common/entity/BaseEntity.java
  src/main/java/com/core/backend/group/application/GroupCommandService.java
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/group/infra/GroupRepositoryImpl.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupInfoResponse.java
  src/main/java/com/core/backend/user/domain/repository/UserRepository.java
  src/main/java/com/core/backend/user/infra/database/UserRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/infra/JpaUserGroupRepository.java
  src/main/java/com/core/backend/usergroup/domain/infra/UserGroupRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/repository/UserGroupRepository.java
  src/test/java/com/core/backend/group/GroupServiceTestFixture.java
  src/test/java/com/core/backend/group/application/GroupCommandServiceTest.java
  src/test/java/com/core/backend/group/application/GroupQueryServiceTest.java
  src/test/java/com/core/backend/usergroup/domain/infra/JpaUserGroupRepositoryTest.java
Labels: 모임, be, 모임방조회

#62 사용자 결제계좌 등록 기능 API 작성
  src/main/java/com/core/backend/account/application/AccountCommandService.java
  src/main/java/com/core/backend/account/application/AccountQueryService.java
  src/main/java/com/core/backend/account/application/dto/AccountRegisterServiceRequest.java
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/account/domain/BankCode.java
  src/main/java/com/core/backend/account/domain/repository/AccountRepository.java
  src/main/java/com/core/backend/account/exception/AccountException.java
  src/main/java/com/core/backend/account/infra/AccountRepositoryImpl.java
  src/main/java/com/core/backend/account/infra/JpaAccountRepository.java
  src/main/java/com/core/backend/account/ui/AccountController.java
  src/main/java/com/core/backend/account/ui/dto/AccountRegisterRequest.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/common/repsonse/ResultResponse.java
  src/main/java/com/core/backend/group/application/dto/GroupRegisterServiceRequest.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupRegisterRequest.java
  src/main/java/com/core/backend/user/ui/UserController.java
  src/test/java/com/core/backend/ServiceTestEnvSupport.java
  src/test/java/com/core/backend/account/AccountServiceTestFixture.java
  src/test/java/com/core/backend/account/application/AccountCommandServiceTest.java
  src/test/java/com/core/backend/group/GroupServiceTestFixture.java
Labels: be, 결제, 계좌등록

#63 대표계좌 등록 및 해제 기능 API 작성
  src/main/java/com/core/backend/account/application/AccountCommandService.java
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/account/domain/repository/AccountRepository.java
  src/main/java/com/core/backend/account/infra/AccountRepositoryImpl.java
  src/main/java/com/core/backend/account/infra/JpaAccountRepository.java
  src/main/java/com/core/backend/account/ui/AccountController.java
  src/main/java/com/core/backend/account/ui/dto/AccountMarkResponse.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/common/mock/controller/GroupMockController.java
  src/main/java/com/core/backend/config/WebConfig.java
  src/main/java/com/core/backend/group/application/GroupCommandService.java
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/group/infra/GroupRepositoryImpl.java
  src/main/java/com/core/backend/group/ui/dto/GroupInfoResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupInviteResponse.java
  src/main/java/com/core/backend/user/infra/database/UserRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/infra/JpaUserGroupRepository.java
  src/main/java/com/core/backend/usergroup/domain/infra/UserGroupRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/repository/UserGroupRepository.java
  src/main/java/com/core/backend/usergroup/exception/UserGroupException.java
Labels: be, 계좌등록, 대표계좌

#64 Feature/#55 개발서버 반영
  src/main/java/com/core/backend/account/application/AccountCommandService.java
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/account/domain/repository/AccountRepository.java
  src/main/java/com/core/backend/account/infra/AccountRepositoryImpl.java
  src/main/java/com/core/backend/account/infra/JpaAccountRepository.java
  src/main/java/com/core/backend/account/ui/AccountController.java
  src/main/java/com/core/backend/account/ui/dto/AccountMarkResponse.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/common/mock/controller/GroupMockController.java
  src/main/java/com/core/backend/config/WebConfig.java
  src/main/java/com/core/backend/group/application/GroupCommandService.java
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/group/infra/GroupRepositoryImpl.java
  src/main/java/com/core/backend/group/ui/dto/GroupInfoResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupInviteResponse.java
  src/main/java/com/core/backend/user/infra/database/UserRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/infra/JpaUserGroupRepository.java
  src/main/java/com/core/backend/usergroup/domain/infra/UserGroupRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/repository/UserGroupRepository.java
  src/main/java/com/core/backend/usergroup/exception/UserGroupException.java
Labels: be

#65 모임방 상세페이지 (기정산내역) 조회 기능 API 작성
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupMemberResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupSettlementListResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupSettlementResponse.java
  src/main/java/com/core/backend/settlement/application/SettlementCommandService.java
  src/main/java/com/core/backend/settlement/application/SettlementQueryService.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/settlement/domain/SettlementRepository.java
  src/main/java/com/core/backend/settlement/infra/JpaSettlementRepository.java
  src/main/java/com/core/backend/settlement/infra/SettlementRepositoryImpl.java
  src/main/java/com/core/backend/settlement/ui/SettlementController.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/java/com/core/backend/usergroup/domain/infra/JpaUserGroupRepository.java
  src/main/java/com/core/backend/usergroup/domain/infra/UserGroupRepositoryImpl.java
  src/main/java/com/core/backend/usergroup/domain/repository/UserGroupRepository.java
Labels: 모임, be, 모임상세페이지

#71 멤버들에게 정산을 요청하는 기능 API 작성
  src/main/java/com/core/backend/account/application/AccountCommandService.java
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/participant/domain/repository/ParticipantRepository.java
  src/main/java/com/core/backend/participant/infra/ParticipantRepositoryImpl.java
  src/main/java/com/core/backend/settlement/application/SettlementCommandService.java
  src/main/java/com/core/backend/settlement/application/dto/SettlementParticipantServiceRequest.java
  src/main/java/com/core/backend/settlement/application/dto/SettlementRegisterServiceRequest.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/settlement/domain/SettlementRepository.java
  src/main/java/com/core/backend/settlement/infra/SettlementRepositoryImpl.java
  src/main/java/com/core/backend/settlement/ui/SettlementController.java
  src/main/java/com/core/backend/settlement/ui/dto/SettlementParticipantRequest.java
  src/main/java/com/core/backend/settlement/ui/dto/SettlementParticipantResponse.java
  src/main/java/com/core/backend/settlement/ui/dto/SettlementRegisterRequest.java
  src/main/java/com/core/backend/user/domain/repository/UserRepository.java
  src/main/java/com/core/backend/user/infra/database/UserRepositoryImpl.java
  src/main/resources/application.yml
  src/test/java/com/core/backend/ServiceTestEnvSupport.java
  src/test/java/com/core/backend/account/AccountServiceTestFixture.java
  src/test/java/com/core/backend/account/application/AccountCommandServiceTest.java
  src/test/java/com/core/backend/group/GroupServiceTestFixture.java
  src/test/java/com/core/backend/group/application/GroupCommandServiceTest.java
  src/test/java/com/core/backend/group/application/GroupQueryServiceTest.java
  src/test/java/com/core/backend/settlement/SettlementServiceTestFixture.java
  src/test/java/com/core/backend/settlement/application/SettlementCommandServiceTest.java
Labels: be, 정산, 정산요청

#74 마이페이지 정보 조회 기능 API 작성
  src/main/java/com/core/backend/settlement/application/SettlementCommandService.java
  src/main/java/com/core/backend/settlement/application/SettlementQueryService.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/user/application/UserQueryService.java
  src/main/java/com/core/backend/user/ui/UserController.java
  src/main/java/com/core/backend/user/ui/dto/UserMyPageResponse.java
Labels: 마이페이지, be, 회원

#77 요청받은 정산내역 동의 기능 API 작성
  src/main/java/com/core/backend/account/ui/AccountController.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/backend/participant/application/ParticipantCommandService.java
  src/main/java/com/core/backend/participant/application/ParticipantQueryService.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/participant/domain/repository/ParticipantRepository.java
  src/main/java/com/core/backend/participant/infra/JpaParticipantRepository.java
  src/main/java/com/core/backend/participant/infra/ParticipantRepositoryImpl.java
  src/main/java/com/core/backend/participant/ui/ParticipantController.java
  src/main/java/com/core/backend/settlement/application/SettlementCommandService.java
  src/main/java/com/core/backend/settlement/application/SettlementQueryService.java
  src/main/java/com/core/backend/settlement/ui/SettlementController.java
  src/main/resources/static/favicon.ico
  src/test/java/com/core/backend/RepositoryTestEnvSupport.java
  src/test/java/com/core/backend/participant/infra/JpaParticipantRepositoryTest.java
  src/test/java/com/core/backend/participant/infra/JpaParticipantRepositoryTestFixture.java
  src/test/java/com/core/backend/usergroup/domain/infra/JpaUserGroupRepositoryTest.java
Labels: be, 정산, 정산요청동의

#78 계좌로부터 스르륵 포인트 환전 기능 API 작성
  src/main/java/com/core/backend/account/application/AccountCommandService.java
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/account/domain/repository/AccountRepository.java
  src/main/java/com/core/backend/account/infra/AccountRepositoryImpl.java
  src/main/java/com/core/backend/account/infra/JpaAccountRepository.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/group/application/GroupCommandService.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/CreateGroupResponse.java
  src/main/java/com/core/backend/point/application/PointCommandService.java
  src/main/java/com/core/backend/point/application/PointQueryService.java
  src/main/java/com/core/backend/point/application/dto/PointConversionServiceRequest.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/point/domain/repository/PointRepository.java
  src/main/java/com/core/backend/point/exception/PointException.java
  src/main/java/com/core/backend/point/infra/JpaPointRepository.java
  src/main/java/com/core/backend/point/infra/PointRepositoryImpl.java
  src/main/java/com/core/backend/point/ui/PointController.java
  src/main/java/com/core/backend/point/ui/dto/PointConversionRequest.java
  src/main/java/com/core/backend/point/ui/dto/PointConversionResponse.java
  src/main/java/com/core/backend/point/ui/dto/PointInfoResponse.java
  src/main/java/com/core/backend/user/application/UserCommandService.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/resources/static/favicon.ico
Labels: be, 포인트전환

#80 참여자의 정산 동의 여부에 따른 포인트 정산 결제 기능 API 작성
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/account/domain/repository/AccountRepository.java
  src/main/java/com/core/backend/account/infra/AccountRepositoryImpl.java
  src/main/java/com/core/backend/account/infra/JpaAccountRepository.java
  src/main/java/com/core/backend/common/exception/ErrorCode.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/point/application/PointCommandService.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/settlement/application/SettlementCommandService.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/settlement/ui/SettlementController.java
  src/main/java/com/core/backend/settlement/ui/dto/CompletedSettlementResponse.java
  src/test/java/com/core/backend/settlement/application/SettlementCommandServiceTest.java
Labels: be, 정산, qr

#82 모임 상세 페이지 API 분리
  src/main/java/com/core/backend/group/application/GroupQueryService.java
  src/main/java/com/core/backend/group/ui/GroupController.java
  src/main/java/com/core/backend/group/ui/dto/GroupMemberResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupSettlementListResponse.java
  src/main/java/com/core/backend/group/ui/dto/GroupSettlementResponse.java
  src/test/java/com/core/backend/group/GroupServiceTestFixture.java
  src/test/java/com/core/backend/group/application/GroupQueryServiceTest.java
  src/test/java/com/core/backend/settlement/SettlementServiceTestFixture.java
Labels: 모임, be, 모임상세페이지

#84 modify : 모임방 생성 시 settlemantId 반환 내용 추가
  src/main/java/com/core/backend/settlement/application/SettlementCommandService.java
  src/main/java/com/core/backend/settlement/ui/SettlementController.java
  src/main/java/com/core/backend/settlement/ui/dto/CreateSettlementResponse.java
Labels: be, modify

#90 사용자 정산 결제 기능 API 테스트 추가
  src/main/java/com/core/backend/settlement/ui/SettlementController.java
  src/test/java/com/core/backend/account/application/AccountCommandServiceTest.java
  src/test/java/com/core/backend/settlement/SettlementServiceTestFixture.java
  src/test/java/com/core/backend/settlement/application/SettlementCommandServiceTest.java
Labels: be, 정산, qr

#92 은행코드 내용 ui에 맞게 변경
  src/main/java/com/core/backend/account/domain/BankCode.java
  src/main/java/com/core/backend/usergroup/domain/UserGroup.java
  src/test/java/com/core/backend/account/JpaAccountRepositoryFixture.java
  src/test/java/com/core/backend/account/application/AccountCommandServiceTest.java
  src/test/java/com/core/backend/account/infra/JpaAccountRepositoryTest.java
  src/test/java/com/core/backend/usergroup/infra/JpaUserGroupRepositoryTest.java
Labels: 결제수단, be, 대표계좌

#95 fix docker compose to change log path
  .docker/docker-compose.yml
Labels: be, 프로젝트세팅

#96 modify : 계좌 최초 등록시 자동으로 대표계좌 등록되도록 수정
  src/main/java/com/core/backend/account/application/AccountCommandService.java
  src/main/java/com/core/backend/point/ui/PointController.java
  src/test/java/com/core/backend/account/application/AccountCommandServiceTest.java
Labels: 결제수단, be, 계좌등록

#98 포인트 환전 기능 API 작성
  .docker/docker-compose.yml
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/participant/ui/dto/GroupParticipantResponse.java
  src/main/java/com/core/backend/point/application/PointCommandService.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/point/ui/PointController.java
  src/main/resources/logback-spring.xml
  src/test/java/com/core/backend/account/AccountServiceTestFixture.java
Labels: be, 포인트전환

#99 fix log path
  src/main/resources/logback-spring.xml
Labels: be, 프로젝트세팅

#100 논리 삭제에 대비한 도메인별 조회 조건 추가
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/common/entity/BaseEntity.java
  src/main/java/com/core/backend/common/mock/data/GetGroupSettlementDetailMockData.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/java/com/core/backend/usergroup/domain/UserGroup.java
Labels: be

#101 baseEntity 미등록으로 인한 테스트 오류 해결
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/point/application/PointCommandService.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/resources/application.yml
  src/test/java/com/core/backend/ServiceTestEnvSupport.java
Labels: be

#102 fix : 로그 오류 해결
  .docker/docker-compose.yml
  src/main/java/com/core/backend/settlement/ui/dto/SettlementDetailResponse.java
  src/main/resources/logback-spring.xml
Labels: be

#103 fix : 배포시 병렬 빌드 제거
  .github/workflows/deploy.yml
Labels: be

#104 fix : @SQLRestriction 제거
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/java/com/core/backend/usergroup/domain/UserGroup.java
Labels: be

#105 feat#100 이전으로 rollback
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
Labels: be

#107 fix : SQLRestriction 재추가
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/java/com/core/backend/usergroup/domain/UserGroup.java
Labels: be

#109 fix : SQLRestriction 관련 오류 수정
  src/main/java/com/core/backend/account/domain/Account.java
  src/main/java/com/core/backend/group/domain/Group.java
  src/main/java/com/core/backend/participant/domain/Participant.java
  src/main/java/com/core/backend/point/domain/Point.java
  src/main/java/com/core/backend/settlement/domain/Settlement.java
  src/main/java/com/core/backend/user/domain/User.java
  src/main/java/com/core/backend/usergroup/domain/UserGroup.java
Labels: be
